server:
  port: 9010
spring:
  application:
    name: test-eureka #name必须一样，不然高可用会导致unavailable-replicas
eureka:
  instance:
    hostname: test-eureka1
#    health-check-url-path: /actuator/health
#    prefer-ip-address: true  #使用ip注册到注册中心
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}  #注册中心显示的服务的名字
#    ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://test-eureka2:9011/eureka/