server:
  port: 9010
spring:
  application:
    name: test-eureka
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
eureka:
  instance:
    hostname: test-eureka
#    ip-address: true
#    health-check-url-path: /actuator/health
#    prefer-ip-address: true  #使用ip注册到注册中心
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}  #注册中心显示的服务的名字
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    #### 清理间隔（单位毫秒，默认是60*1000），开发环境设置如下可快速移除不可用的服务
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
