spring:
  profiles:
    active: db
  application:
    name: oauth-server
  ##### Thymeleaf #####
  # 编码
  thymeleaf:
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    encoding: UTF-8
    # 热部署静态文件
    cache: false #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    # 使用HTML5标准
    mode: HTML5




server:
  port: 10011
#  servlet:
#    context-path: /auth


ribbon:
  eureka:
    enabled: true
  ConnectTimeout: 10000 # ribbon链接超时时长
  ReadTimeout: 10000 # ribbon读取超时时间长
eureka:
  client:
    #    registerWithEureka: false
    #    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:9010/eureka/
  instance:
    #    ip-address: 172.16.0.164 #prefer-ip-address：true 当前服务指定ip 注册到eureka
    health-check-url-path: /actuator/health
    prefer-ip-address: true  #使用ip注册到注册中心
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  #注册中心显示的服务的名字