spring:
  profiles:
    active: 'db'
  application:
    name: oauth-resource

server:
  port: 10021

ribbon:
  eureka:
    enabled: true
  ConnectTimeout: 10000 # ribbon链接超时时长
  ReadTimeout: 10000 # ribbon读取超时时间长
eureka:
  client:
    #    registerWithEureka: false
    #    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:9010/eureka/
  instance:
    #    ip-address: 172.16.0.164 #prefer-ip-address：true 当前服务指定ip 注册到eureka
    health-check-url-path: /actuator/health
    prefer-ip-address: true  #使用ip注册到注册中心
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  #注册中心显示的服务的名字

#security:
#  oauth2:
#    resource:
#      token-info-uri: http://localhost:10011/oauth/check_token
#      prefer-token-info: true
#    client:
#      access-token-uri: http://localhost:10011/oauth/token
#      user-authorization-uri: http://localhost:10011/oauth/authorize
#      client-id: resource
#      client-secret: resource
